#!/bin/bash

# replace appname with your app name
APP=fastapi

APPDIR=$HOME/apps/$APP

# set HANDLER to your ASGI handler, eg for `myproject/asgi.py` use:
HANDLER=fastapi.main

# set PORT to your app's port:
PORT=64997

STARTCMD="$APPDIR/env/bin/gunicorn main:application --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 127.0.0.1:$PORT"

pgrep -f "$STARTCMD" > /dev/null && pkill -f "$STARTCMD" && echo "stopped $APP." || echo "$APP not running."